{{- if hasKey .Values.kubernetes "namespace" -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kubernetes.namespace }}
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: pipelines
{{- end -}}
